FROM ubuntu:18.04

# TODO:
# - Configure the container (sources, UTC timezone, update packages, install common packages)
# - Create captain user
# - Install PHP (ondrej)
# - Install nginx
# - Install supervisor
